# Create the cleaned soybean research dataset for R
soybean.hi.data <- data.frame(
  Paper_ID = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 14, 14, 15, 16, 17, 18, 19, 20, 
               21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 37, 37, 
               38, 39, 39, 40, 41, 42, 43),
  Title = c(
    "Development, growth and yield of late-sown soybeans in the southern Pampas",
    "Variability of Biomass and Harvest Index from Several Soybean Genotypes as Renewable Energy Source",
    "Characteristics of Yield and Harvest Index, and Evaluation of Balanced Nutrient Uptake of Soybean in Northeast China",
    "Responses of Soybean Genotypes to Different Nitrogen and Phosphorus Sources: Impacts on Yield Components, Seed Yield, and Seed Protein",
    "Effect of irrigation regime on yield, harvest index and water productivity of soybean",
    "Planting time and variety effects on biomass, harvest index, and yield of irrigated soybean in mid-Southern United States",
    "Effect of varieties and population of intercropped soybean with maize on yield and yield components at Haro Sabu, Western Ethiopia",
    "Physiological Plant Response Differences among High- and Average-Yield Soybean Areas in Arkansas",
    "Both biomass accumulation and harvest index drive the yield improvements in soybean at high and low phosphorus in south-west China",
    "Stability of Soybean Harvest Index",
    "Soybean Biomass and Nitrogen Accumulation Rates and Radiation Use Efficiency in a Maximum Yield Environment",
    "Influences of different planting times on harvest index and yield determination factors in soybean",
    "Effect of Cultivar and Planting Pattern on Yield and Apparent Harvest index in soybean",
    "Effect of Cultivar and Planting Pattern on Yield and Apparent Harvest index in soybean",
    "Effect of Cultivar and Planting Pattern on Yield and Apparent Harvest index in soybean",
    "Dry matter accumulation, harvest index and yield of soybean in response to planting time",
    "Soybean Yield Response to Narrow Rows Is Largely due to Enhanced Early Growth",
    "The effects of increased temperature on crop growth and yield of soybean grown in a temperature gradient chamber",
    "Assessment of Yield and Yield Component of Soybean Genotypes in north of Khuzestan",
    "Soybean Seed Yield Performances under Different Cultural practices",
    "Assimilatory Capacity Effects on Soybean Yield Components and Pod Number",
    "Biomass, Harvest Index and Yield in Relation to changes in photo-thermal regimes in soybean genotypes",
    "Plant density effects on growth, yield and yield components of two soybean varieties under equidistant planting arrangement",
    "Characteristics of Yield and Harvest Index, and Evaluation of Balanced Nutrient Uptake of Soybean in Northeast China",
    "Relationships Between Harvest Indices and other Plant Characteristics in Soybean",
    "Studying the Effects of Different Planting Dates on Biological Yield, Harvest Index and Some Morphological Features of Soybean Cultivars in Cold Region of Ardabil",
    "Effect of Sowing Date on Yield and Seed Quality of Soybean",
    "Yield and yield Components of Soybean Cultivars as Affected by Planting Date",
    "BIOLOGICAL AND INORGANIC FERTILIZER APPLICATIONS IMPROVED GROWTH, NODULATION AND YIELD OF SOYBEAN",
    "Lodging dynamics and seed yield for two soybean genotypes with contrasting lodging-susceptibility",
    "Assessing soybean yield in Madhya Pradesh by using a multi-model approach",
    "COMPARISON OF YIELD PERFORMANCE OF SOYBEAN VARIETIES UNDER SEMI-ARID CONDITIONS",
    "Response of soybean varieties to different sowing times",
    "Changes in soybean cultivars released over the past 50 years in southern Brazil",
    "Yield and water-use related traits in landrace and new soybean cultivars in arid and semi-arid areas of China",
    "Effect of Preplant Fertilizer on Agronomic and Physiological Traits of Soybean Cultivars from Different Breeding Programs",
    "Soybean profitability and yield component response to nitrogen fertilizer in Iowa",
    "Physiological and Phenological Responses of Historical Soybean Cultivar Releases to Earlier Planting",
    "Physiological and Phenological Responses of Historical Soybean Cultivar Releases to Earlier Planting",
    "Physiological and Phenological Responses of Historical Soybean Cultivar Releases to Earlier Planting",
    "Interplay between nitrogen fertilizer and biological nitrogen fixation in soybean: implications on seed yield and biomass allocation",
    "Agronomic traits of soybean cultivars released in different decades after grafting record-yield cultivar as rootstock",
    "Agronomic traits of soybean cultivars released in different decades after grafting record-yield cultivar as rootstock",
    "Historical gains in soybean seed yield are driven by linear increases in light interception, energy conversion, and partitioning efficiencies",
    "Shifts in Soybean Yield, Nutrient Uptake, and Nutrient Stoichiometry: A Historical Synthesis-Analysis",
    "Harvest Index of Soybeans as Affected by Planting Date and Maturity Rating",
    "High-yield factors in the new soybean cultivar 'Soramizuki' derived from a US parent cultivar"
  ),
  Paper_Year = c(2003, 2015, 2019, 2022, 2018, 2024, 2015, 2018, 2022, 1984, 2014, 2000, 
                 1984, 1984, 1984, 2002, 1998, 2013, 2018, 2009, 1995, 2011, 2011, 2019, 
                 1980, 2011, 2016, 2013, 2018, 2025, 2025, 2013, 2017, 2022, 2022, 2010, 
                 2020, 2014, 2014, 2014, 2018, 2017, 2017, 2014, 2018, 1979, 2025),
  Country = c("Argentina", "Indonesia", "China", "Philippines", "Serbia", "USA", "Ethiopia", 
              "USA", "China", "USA", "USA", "Korea", "USA", "USA", "USA", "Korea", "USA", 
              "Japan", "Iran", "Turkey", "USA", "India", "Bangladesh", "China", "USA", 
              "Iran", "Bangladesh", "Iran", "Ethiopia", "Argentina", "India", "Pakistan", 
              "India", "Brazil", "China", "China", "USA", "USA", "USA", "USA", "USA", 
              "China & USA", "China & USA", "USA", "USA", "USA", "Japan"),
  State = c("Pampas", "East Java", "Liaoning", "Cambodia", "Vojvodina", "Mississippi", 
            "Haro Sabu", "Arkansas", "Guizhou", "Florida", "Missouri", "Seoul", "Ohio", 
            "Ohio", "Ohio", "Seoul", "Illinois", "Kyoto", "Khuzestan", "Bursa", "Louisiana", 
            "Punjab", "Mymensingh", "Liaoning", "Indiana", "Ardabil", "Dhaka", "Ilam", 
            "Addis Ababa", "Zavalla", "Madhya Pradesh", "Faisalabad", "Tirupati", "Parana", 
            "Yuzhong", "Liaoning", "Iowa", "Wisconsin", "Illinois", "Indiana", "Midwest", 
            "Liaoning", "Ohio", "Illinois", "Kansas", "Missouri", "Ibaraki"),
  Lat = c(-35.0000, -7.6400, 41.0000, 12.5657, 44.8667, 33.4647, 8.4175, 34.7465, 26.8154, 
          29.6516, 36.8408, 37.5901, 40.7984, 41.1269, 40.2592, 37.5901, 40.0000, 35.0000, 
          32.0389, 40.2581, 30.6954, 31.1040, 24.7470, 41.0450, 40.4169, 38.2484, 23.8103, 
          33.6167, 9.0300, -33.0167, 22.7000, 31.5204, 13.6288, -23.5505, 29.6667, 41.8057, 
          42.0570, 43.2955, 40.1106, 40.4169, 41.5000, 41.2955, 40.4173, 40.0000, 39.1836, 
          38.9500, 36.0000),
  Long = c(-62.0000, 112.9125, 123.0000, 104.9910, 20.3333, -90.5478, 34.7361, -92.2896, 
           106.8744, -82.3246, -94.2556, 127.0020, -81.9351, -83.6817, -82.5523, 127.0020, 
           -88.2073, 135.5000, 48.4056, 28.8942, -91.1390, 75.1469, 90.4113, 122.1950, 
           -86.8753, 48.2946, 90.4143, 46.4667, 38.7400, -60.8833, 75.8000, 73.6833, 
           79.4192, -51.8550, 106.5667, 123.4315, -93.8760, -89.3676, -88.2073, -86.8753, 
           -90.0000, 122.3417, -82.9071, -88.2333, -96.5717, -92.3300, 140.0100),
  Research_Focus = c("Late sowing effects", "Biomass variability", "Yield components", 
                     "Nutrient responses", "Irrigation effects", "Planting time", 
                     "Intercropping", "Physiological responses", "Phosphorus effects", 
                     "Harvest index stability", "Radiation efficiency", "Planting time", 
                     "Cultivar patterns", "Cultivar patterns", "Cultivar patterns", 
                     "Planting time", "Row spacing", "Temperature effects", 
                     "Genotype assessment", "Cultural practices", "Assimilatory capacity", 
                     "Photo-thermal regimes", "Plant density", "Nutrient uptake", 
                     "Harvest index relationships", "Planting dates", "Sowing date", 
                     "Planting date", "Fertilizer effects", "Lodging dynamics", 
                     "Yield modeling", "Variety comparison", "Sowing times", 
                     "Cultivar changes", "Water-use traits", "Fertilizer effects", 
                     "Nitrogen response", "Historical cultivars", "Historical cultivars", 
                     "Historical cultivars", "Nitrogen fixation", "Grafting effects", 
                     "Grafting effects", "Yield efficiency", "Nutrient stoichiometry", 
                     "Harvest index", "High-yield factors")
)

str(soybean.hi.data)
head(soybean.hi.data)

# Save to CSV for use in other analyses
write.csv(soybean.hi.data, "data.cleaned.csv", row.names = FALSE)
